import type { z } from "zod";
import { productSchema } from "@vortex/shared";

type ProductSeedInput = z.input<typeof productSchema> & { slug: string };

export const PRODUCTS_SEED: ProductSeedInput[] = [
  {
    slug: "dragao-articulado",
    name: "Dragão Articulado",
    category: "figurines",
    emoji: "🐉",
    price: 89.9,
    badge: "hot",
    description:
      "Dragão articulado em PLA de alta qualidade, impresso em uma peça única sem suportes. 18cm de comprimento.",
    colors: ["Preto", "Vermelho", "Dourado", "Verde"],
    material: "PLA",
    specs: { Altura: "18cm", Peso: "120g", Resolução: "0.1mm", Material: "PLA", Prazo: "24-48h" },
    stock: 40,
  },
  {
    slug: "suporte-para-celular",
    name: "Suporte para Celular",
    category: "tech",
    emoji: "📱",
    price: 34.9,
    oldPrice: 49.9,
    badge: "sale",
    description:
      "Suporte articulado para celular, compatível com todos os modelos. Fixação por ventosa ou base plana.",
    colors: ["Preto", "Branco", "Cinza"],
    material: "PETG",
    specs: { Altura: "15cm", Peso: "45g", Resolução: "0.15mm", Material: "PETG", Prazo: "24h" },
    stock: 60,
  },
  {
    slug: "vaso-geometrico",
    name: "Vaso Geométrico",
    category: "decor",
    emoji: "🏺",
    price: 59.9,
    badge: "new",
    description:
      "Vaso com design geométrico moderno, perfeito para plantas suculentas e cactos. 100% impermeabilizado.",
    colors: ["Branco", "Preto", "Terracota", "Azul"],
    material: "PLA",
    specs: { Altura: "20cm", Peso: "180g", Resolução: "0.2mm", Material: "PLA", Prazo: "48h" },
    stock: 25,
  },
  {
    slug: "engrenagem-industrial",
    name: "Engrenagem Industrial",
    category: "industrial",
    emoji: "⚙️",
    price: 149.9,
    description:
      "Engrenagem de precisão para uso industrial. Tolerâncias de ±0.1mm. Disponível em vários módulos.",
    colors: ["Preto"],
    material: "PETG",
    specs: { Diâmetro: "80mm", Peso: "210g", Tolerância: "±0.1mm", Material: "PETG", Prazo: "48h" },
    stock: 15,
  },
  {
    slug: "mini-t-rex",
    name: "Mini T-Rex",
    category: "toys",
    emoji: "🦖",
    price: 44.9,
    badge: "new",
    description: "T-Rex articulado para colecionadores e presentes. Detalhamento incrível com escamas em relevo.",
    colors: ["Verde", "Cinza", "Laranja", "Preto"],
    material: "PLA",
    specs: { Altura: "12cm", Peso: "65g", Resolução: "0.1mm", Material: "PLA", Prazo: "24h" },
    stock: 50,
  },
  {
    slug: "suporte-de-mesa-modular",
    name: "Suporte de Mesa Modular",
    category: "tech",
    emoji: "🖥️",
    price: 79.9,
    description:
      "Sistema modular de organização de mesa. Compartimentos para canetas, cabos, cartões e muito mais.",
    colors: ["Preto", "Branco", "Cinza"],
    material: "PLA",
    specs: { Dimensões: "30x20cm", Peso: "320g", Resolução: "0.2mm", Material: "PLA", Prazo: "48h" },
    stock: 30,
  },
  {
    slug: "chaveiro-personalizado",
    name: "Chaveiro Personalizado",
    category: "figurines",
    emoji: "🗝️",
    price: 19.9,
    description: "Chaveiro personalizado com nome, logo ou design exclusivo. Tamanho 5cm.",
    colors: ["Várias"],
    material: "PLA",
    specs: { Tamanho: "5cm", Peso: "8g", Resolução: "0.1mm", Material: "PLA", Prazo: "24h" },
    stock: 100,
  },
  {
    slug: "peca-de-reposicao-custom",
    name: "Peça de Reposição Custom",
    category: "industrial",
    emoji: "🔧",
    price: 199.9,
    description: "Impressão de peças de reposição sob medida. Envie suas medidas ou arquivo CAD para orçamento.",
    colors: ["Conforme projeto"],
    material: "Conforme projeto",
    specs: { Dimensões: "Conforme projeto", Resolução: "±0.1mm", Material: "Conforme", Prazo: "72h" },
    stock: 10,
  },
];
