import "reflect-metadata";
import { DataSource } from "typeorm";
import { env } from "./env";
import {
  Address,
  Asset,
  BlingCredential,
  CartItem,
  Coupon,
  CustomQuoteRequest,
  ExpenseCategory,
  ExpenseEntry,
  Filament,
  FilamentMovement,
  Order,
  OrderItem,
  Payment,
  PrintJob,
  Printer,
  PrinterMaintenanceLog,
  Product,
  PurchaseOrder,
  PurchaseOrderItem,
  RecurringExpense,
  StoreSettings,
  Supplier,
  Supply,
  SupplyMovement,
  User,
} from "../entities";

export const AppDataSource = new DataSource({
  type: "postgres",
  url: env.databaseUrl,
  synchronize: false,
  logging: env.nodeEnv === "development" ? ["error", "warn"] : false,
  entities: [
    User,
    Address,
    BlingCredential,
    Product,
    CartItem,
    Coupon,
    Order,
    OrderItem,
    Payment,
    CustomQuoteRequest,
    StoreSettings,
    Filament,
    FilamentMovement,
    Printer,
    PrinterMaintenanceLog,
    PrintJob,
    Supplier,
    PurchaseOrder,
    PurchaseOrderItem,
    ExpenseCategory,
    Supply,
    SupplyMovement,
    Asset,
    RecurringExpense,
    ExpenseEntry,
  ],
  migrations: [__dirname + "/../migrations/*.{ts,js}"],
});
