import "reflect-metadata";
import { DataSource } from "typeorm";
import { env } from "./env";
import {
  Address,
  CartItem,
  Coupon,
  CustomQuoteRequest,
  Filament,
  FilamentMovement,
  Order,
  OrderItem,
  Payment,
  PrintJob,
  Printer,
  PrinterMaintenanceLog,
  Product,
  PurchaseOrder,
  PurchaseOrderItem,
  StoreSettings,
  Supplier,
  User,
} from "../entities";

export const AppDataSource = new DataSource({
  type: "postgres",
  url: env.databaseUrl,
  synchronize: false,
  logging: env.nodeEnv === "development" ? ["error", "warn"] : false,
  entities: [
    User,
    Address,
    Product,
    CartItem,
    Coupon,
    Order,
    OrderItem,
    Payment,
    CustomQuoteRequest,
    StoreSettings,
    Filament,
    FilamentMovement,
    Printer,
    PrinterMaintenanceLog,
    PrintJob,
    Supplier,
    PurchaseOrder,
    PurchaseOrderItem,
  ],
  migrations: [__dirname + "/../migrations/*.{ts,js}"],
});
